name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cr.yandex/crp1kafuq6umi5ce3tra/gateway:latest

    - name: Login in docker repository
      run: docker login --username=oauth --password=AgAAAAABY9CuAATuwQEVgeoN3Uyevi6na295oXM cr.yandex

    - name: Push the Docker image
      run: docker push cr.yandex/crp1kafuq6umi5ce3tra/gateway:latest
