name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn -B package -DskipTests=true --file pom.xml
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version --file pom.xml -q -DforceStdout)
        docker build . --file Dockerfile --tag cr.yandex/crp1kafuq6umi5ce3tra/gateway:$IMAGE_TAG
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} cr.yandex
        docker push cr.yandex/crp1kafuq6umi5ce3tra/gateway:$IMAGE_TAG
